@version: current
@include "scl.conf"

options {
    keep-hostname(yes);
    flush-lines(1);
    dns-cache(no);
};

destination d_postgres {
    python(class("mssql.MSSQL"));
};

# Both UDP and TCP listen on the same port (514 by default)
source s_udp {
    network(
        ip("0.0.0.0") port(514)
        transport("udp")
        flags(syslog-protocol)
    );
};

source s_tcp {
    network(
        ip("0.0.0.0") port(514)
        transport("tcp")
        flags(syslog-protocol)
    );
};

source s_tls {
    network(
        ip("0.0.0.0") port(6514)
        transport("tls")
        flags(syslog-protocol)
        tls(
            key-file("/etc/syslog-ng/certs/server.key")
            cert-file("/etc/syslog-ng/certs/server.crt")
            ca-dir("/etc/syslog-ng/certs/")
            peer-verify(optional-untrusted)
        )
    );
};

log { source(s_udp); source(s_tcp); source(s_tls); destination(d_postgres); };
